const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

const REQUEST_ROBOTS_PENDING = 'REQUEST_ROBOTS_PENDING';
const REQUEST_ROBOTS_SUCCESS = 'REQUEST_ROBOTS_SUCCESS';
const REQUEST_ROBOTS_FAILED = 'REQUEST_ROBOTS_FAILED';

export {CHANGE_SEARCH_FIELD, REQUEST_ROBOTS_PENDING, REQUEST_ROBOTS_FAILED, REQUEST_ROBOTS_SUCCESS};